change-log-file=src/main/resources/db/changelog/liquibase-output.xml
url=jdbc:postgresql://localhost:5432/semester_work_music
username=postgres
password=postgres
driver-class-name=org.postgresql.Driver